services:
  db:
    image: postgres:17-alpine
    container_name: my_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
